"""Local-only FastAPI surface for the storage cleanup dashboard."""

from __future__ import annotations

import secrets
import threading
from dataclasses import dataclass
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from starlette.middleware.trustedhost import TrustedHostMiddleware
from starlette.requests import Request
from starlette.responses import Response

from pig_behavior.storage_cleanup.service import CleanupError, CleanupService

STATIC_ROOT = Path(__file__).with_name("static")


class ScanRequest(BaseModel):
    """Options that do not broaden cleanup authority."""

    include_large_review: bool = False


class PreviewRequest(BaseModel):
    """Opaque tokens from the latest server-side scan."""

    tokens: list[str] = Field(min_length=1, max_length=500)


class CommitRequest(BaseModel):
    """Exact confirmation generated by the preview endpoint."""

    confirmation_id: str = Field(min_length=20, max_length=200)
    phrase: str = Field(min_length=1, max_length=100)


@dataclass(slots=True)
class CommitJob:
    """One local recycle operation with item-level progress."""

    job_id: str
    total_count: int
    status: str = "queued"
    completed_count: int = 0
    current_name: str | None = None
    recycled_count: int = 0
    failed_count: int = 0
    reclaimed_bytes: int = 0
    error: str | None = None

    def to_public_dict(self) -> dict[str, object]:
        """Return progress without exposing new filesystem authority."""

        return {
            "job_id": self.job_id,
            "status": self.status,
            "total_count": self.total_count,
            "completed_count": self.completed_count,
            "current_name": self.current_name,
            "recycled_count": self.recycled_count,
            "failed_count": self.failed_count,
            "reclaimed_bytes": self.reclaimed_bytes,
            "error": self.error,
        }


class CommitJobStore:
    """Run one confirmed recycle request in the background and expose status."""

    def __init__(self, service: CleanupService) -> None:
        self._service = service
        self._jobs: dict[str, CommitJob] = {}
        self._lock = threading.RLock()

    def start(self, payload: CommitRequest) -> dict[str, object]:
        """Create a local job; validation remains inside CleanupService."""

        job = CommitJob(
            job_id=secrets.token_urlsafe(18),
            total_count=0,
        )
        with self._lock:
            self._jobs[job.job_id] = job
        thread = threading.Thread(
            target=self._run,
            args=(job.job_id, payload),
            daemon=True,
            name="storage-recycle-job",
        )
        thread.start()
        return job.to_public_dict()

    def get(self, job_id: str) -> dict[str, object]:
        """Return one opaque job's current local status."""

        with self._lock:
            job = self._jobs.get(job_id)
            if job is None:
                raise CleanupError("Recycle job was not found.")
            return job.to_public_dict()

    def _run(self, job_id: str, payload: CommitRequest) -> None:
        def report(
            completed: int,
            total: int,
            item: object,
            status: str,
        ) -> None:
            with self._lock:
                job = self._jobs[job_id]
                job.status = "running"
                job.total_count = total
                job.completed_count = completed
                job.current_name = getattr(item, "display_name", None)
                if status == "failed":
                    job.failed_count += 1

        try:
            result = self._service.commit(
                payload.confirmation_id,
                payload.phrase,
                progress=report,
            )
        except CleanupError as exc:
            with self._lock:
                job = self._jobs[job_id]
                job.status = "failed"
                job.error = str(exc)
            return
        except Exception:
            with self._lock:
                job = self._jobs[job_id]
                job.status = "failed"
                job.error = "Recycle job stopped unexpectedly."
            return
        with self._lock:
            job = self._jobs[job_id]
            job.status = "complete"
            job.completed_count = job.total_count
            job.current_name = None
            job.reclaimed_bytes = int(result["reclaimed_bytes"])
            job.recycled_count = int(result["recycled_count"])
            job.failed_count = int(result["failed_count"])


def create_app(service: CleanupService | None = None) -> FastAPI:
    """Create an isolated application with no product API routes."""

    cleanup_service = service or CleanupService()
    commit_jobs = CommitJobStore(cleanup_service)
    app = FastAPI(
        title="Agent Storage Guard",
        docs_url=None,
        redoc_url=None,
        openapi_url=None,
    )
    app.add_middleware(
        TrustedHostMiddleware,
        allowed_hosts=["127.0.0.1", "localhost", "testserver"],
    )

    @app.middleware("http")
    async def add_security_headers(request: Request, call_next) -> Response:
        response = await call_next(request)
        response.headers["Cache-Control"] = "no-store"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Referrer-Policy"] = "no-referrer"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; script-src 'self'; style-src 'self'; "
            "connect-src 'self'; img-src 'self' data:; object-src 'none'; "
            "base-uri 'none'; form-action 'self'; frame-ancestors 'none'"
        )
        return response

    @app.get("/")
    def dashboard() -> FileResponse:
        return FileResponse(STATIC_ROOT / "index.html")

    @app.get("/assets/app.css")
    def stylesheet() -> FileResponse:
        return FileResponse(STATIC_ROOT / "app.css", media_type="text/css")

    @app.get("/assets/app.js")
    def javascript() -> FileResponse:
        return FileResponse(
            STATIC_ROOT / "app.js",
            media_type="application/javascript",
        )

    @app.get("/favicon.ico")
    def favicon() -> Response:
        return Response(status_code=204)

    @app.get("/api/health")
    def health() -> dict[str, str]:
        return {"status": "ok", "mode": "local-only", "delete_mode": "recycle-bin"}

    @app.post("/api/scan")
    def scan(payload: ScanRequest) -> dict[str, object]:
        return cleanup_service.scan(
            include_large_review=payload.include_large_review
        )

    @app.post("/api/recycle/preview")
    def preview(payload: PreviewRequest) -> dict[str, object]:
        try:
            return cleanup_service.preview(payload.tokens)
        except CleanupError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @app.get("/api/items/{token}/children")
    def browse(token: str) -> dict[str, object]:
        try:
            return cleanup_service.browse(token)
        except CleanupError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @app.post("/api/recycle/commit")
    def commit(payload: CommitRequest) -> dict[str, object]:
        try:
            return commit_jobs.start(payload)
        except CleanupError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc

    @app.get("/api/recycle/jobs/{job_id}")
    def recycle_job(job_id: str) -> dict[str, object]:
        try:
            return commit_jobs.get(job_id)
        except CleanupError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc

    return app


def run() -> None:
    """Launch only on the loopback interface."""

    import uvicorn

    uvicorn.run(
        "pig_behavior.storage_cleanup.web:create_app",
        factory=True,
        host="127.0.0.1",
        port=8765,
        reload=False,
    )
